/** English source strings. Keep product copy here for a future locale layer. */
export const copy = {
  appName: "Harness",
  skipToMessage: "Skip to message",
  userInitial: "Y",
  repository: "Repository",
  chooseRepository: "Open repository",
  repositoryHint: "Choose where this conversation will work.",
  sessions: "Conversations",
  noSessions: "Saved conversations for this repository appear here.",
  newConversation: "New conversation",
  singleSession: "Close the attached conversation before opening another.",
  conversationsLimited: "Showing the 100 most recently updated conversations.",
  closeConversation: "Close conversation",
  savedConversation: "Saved conversation",
  historyPartial: "Partial local history. Viewing this conversation does not resume native work.",
  historyUnconfirmed: "Some messages have no confirmed native outcome. They will not be sent again automatically.",
  historyIncompatible:
    "To inspect or resume, select the original repository, runtime executable and native account home.",
  historyCheckConnection: "Check the native connection before inspecting or resuming this conversation.",
  inspectConversation: "Inspect native state",
  reconcileConversation: "Reconcile uncertain work",
  resumeConversation: "Resume conversation",
  resumeHint: "Resume keeps the original model and execution policy. Uncertain work must be reconciled first.",
  inspectionUnavailable:
    "This runtime cannot verify uncertain native history. Cleanly closed conversations can resume; uncertain work remains blocked.",
  inspectionState: "Native state",
  inspectionCoverage: "Inspection coverage",
  terminalTurns: "terminal turns",
  runningTurns: "running turns",
  unknownTurns: "unknown turns",
  runtime: "Runtime",
  runtimeSelect: "Choose runtime",
  codex: "Codex",
  claude: "Claude Code",
  connectionChecks: "Connection checks only",
  claudeUnavailable: "Claude Code execution is unavailable. You can check its version and sign-in status here.",
  claudeEmptyTitle: "Connect your Claude Code account.",
  claudeEmptyDescription:
    "Check your installed runtime and sign-in status. Conversations and native Skills activation remain unavailable while billing and managed policy checks are incomplete.",
  openCodePending: "OpenCode · coming next",
  nativeSubscription: "Native subscription",
  localWorkspace: "Local workspace",
  conversation: "Conversation",
  noRepository: "No repository selected",
  refresh: "Refresh connection and context",
  openContext: "Open runtime and context",
  closeContext: "Close context",
  context: "Runtime & context",
  loading: "Connecting to the desktop host…",
  unavailable: "Desktop unavailable",
  missingBridge: "The desktop connection is unavailable. Open Harness from the desktop launcher.",
  failedRequest: "The operation could not be completed. Refresh the connection and try again.",
  dismissError: "Dismiss error",
  emptyTitle: "A workspace for your next idea.",
  emptyDescription: "Open a repository, connect your native runtime, and start a conversation with your code.",
  emptyConfiguredTitle: "Ready when you are.",
  emptyConfiguredDescription:
    "Check your account and execution settings, then start a conversation. Your prompt is only sent when you choose Send.",
  emptySessionTitle: "What are we working on?",
  emptySessionDescription: "Describe the change, ask about this repository, or work through a problem together.",
  emptyFootnote:
    "Your runtime keeps its own account and subscription. Harness never switches to API billing automatically.",
  openSetup: "Set up runtime",
  promptLabel: { codex: "Message to Codex", claude: "Message to Claude Code" },
  promptPlaceholder: "Describe what you want to work on…",
  promptUnavailable: "Start a conversation to send a message…",
  composerHint: "Ctrl + Enter to send",
  composerNote: "Review requests appear in the context panel.",
  send: "Send message",
  interrupt: "Interrupt",
  running: { codex: "Codex is working", claude: "Claude Code is working" },
  awaiting: "Waiting for your review",
  you: "You",
  setup: "Connection",
  authentication: "Account",
  billing: "Billing route",
  overage: "Provider overage",
  unknown: "Unknown",
  subscription: "Subscription",
  observedSubscription: "Subscription observed",
  authenticationStatus: {
    unknown: "Unknown",
    subscription: "Subscription observed",
    authenticated: "Signed in",
    unauthenticated: "Not signed in",
  },
  version: "Version",
  chooseExecutable: { codex: "Choose Codex executable", claude: "Choose Claude Code executable" },
  chooseNativeHome: "Choose native account home",
  selectedExecutable: "Executable",
  selectedNativeHome: "Native account home",
  checkConnection: "Check connection",
  setupHint: {
    codex:
      "Choose your installed Codex executable and the home folder containing .codex, such as C:\\Users\\you. Sign in using Codex before connecting here.",
    claude:
      "Choose your installed Claude Code executable and the home folder containing .claude, such as C:\\Users\\you. Sign in using Claude Code before checking this connection.",
  },
  overageNotice: "Provider overage is unknown. Check your plan and spending settings in Codex before starting.",
  acknowledgeOverage: "I have checked my provider’s spending settings and accept that overage is unknown.",
  allowFileChanges: "Allow file changes in this repository, with review before approval.",
  acknowledgeBoundary: "I understand the operating-system execution boundary is not verified in this preview.",
  modelLabel: "Codex model",
  modelPlaceholder: "Choose a model",
  modelHint: "Models reported by Codex. Availability does not confirm plan access or billing.",
  modelsNotLoaded: "Check connection to load models from your selected Codex runtime.",
  modelsLoading: "Loading models from Codex…",
  modelsUnavailable: "No model catalog is available. Check connection again before starting.",
  modelsUnsupported: "Model selection is unavailable for this runtime.",
  startConversation: "Start conversation",
  sessionStarted: "Conversation connected",
  workspaceReadOnly: "Read-only workspace",
  workspaceWrite: "File changes require review",
  activity: "Activity",
  files: "Files",
  usage: "Usage",
  filesHint: "Browse a bounded set of repository text files. Previews are read-only.",
  refreshFiles: "Refresh files",
  filesNotLoaded: "Refresh to list files in the selected repository.",
  filesEmpty: "No supported text files were found within the preview limits.",
  filesLimited: "The file list reached its preview limit. Some files are omitted.",
  fileBaseline: "Changes are compared with this conversation’s starting files.",
  fileBaselineUnavailable: "The conversation’s starting files are unavailable. A change comparison cannot be shown.",
  filePreview: "File preview",
  fileDiff: "Changes",
  fileText: "Current text",
  fileTextUnavailable: "Current file text is unavailable or the file was deleted.",
  fileUnchanged: "No changes from the conversation’s starting file.",
  fileChange: { added: "Added", modified: "Modified", deleted: "Deleted", unchanged: "Unchanged", unknown: "Unknown" },
  tokenUsage: "Token usage",
  usageCumulative: "Cumulative counts reported by the native runtime. Later updates replace earlier counts.",
  usageLatest: "The latest usage observation reported by the native runtime.",
  usageUnavailable: "The runtime has not reported token usage for this conversation.",
  inputTokens: "Input tokens",
  outputTokens: "Output tokens",
  cachedTokens: "Cached input tokens",
  reasoningTokens: "Reasoning tokens",
  usageRelations:
    "Cached and reasoning counts may be included in the input and output counts; they are not added again.",
  contextUsage: "Context window",
  contextUsed: "Used tokens",
  contextCapacity: "Capacity tokens",
  usageLimit: "Unknown values are not zero. Token counts do not establish remaining quota or provider charges.",
  review: "Review",
  skills: "Skills",
  contextTabs: "Context views",
  activityEmptyTitle: "The work, as it happens",
  activityEmpty: "Tool activity and runtime updates appear here during your conversation.",
  reviewEmptyTitle: "Nothing waiting for review",
  reviewEmpty: "Proposed file changes and questions will appear here when your runtime needs input.",
  fileReview: "File change request",
  permissionReview: "Permission request",
  questionReview: "Your runtime has a question",
  openReview: "Open protected review",
  reviewUnavailable: "Protected review is unavailable. This request can only be declined.",
  questionUnavailable: "Question content is unavailable. Cancel this request to continue safely.",
  reviewed: "Protected content opened",
  expires: "Expires",
  expired: "This review has expired. Open it again to check whether the request is still available.",
  submitAnswers: "Send answers",
  cancelQuestion: "Cancel request",
  movedTo: "Moves to",
  change: { add: "Added", delete: "Deleted", update: "Updated" },
  skillsIntro:
    "Claude Skills discovered in this repository and any selected user skills folder. Discovery is read-only.",
  skillsPending:
    "Skills are cataloged only. Native activation is disabled until runtime execution and policy checks are supported.",
  skillsSelection:
    "Choose the plain skills this Claude conversation may use. The runtime checks each selected file again before starting.",
  skillsSelected: "skill permissions selected",
  skillUserInvocation: "Allow user invocation of",
  skillModelInvocation: "Allow model invocation of",
  skillUnsupported: "This skill’s metadata or native features are unsupported in this version.",
  skillsFixed: "Skill choices are fixed when the conversation starts.",
  skillsEmptyTitle: "Bring your Claude Skills",
  skillsEmpty: "Add SKILL.md files under .claude/skills in this repository, or choose a user skills folder.",
  chooseSkillsRoot: "Choose user skills folder",
  skillsWorkspaceMissing: "Open a repository to discover its Claude Skills.",
  skillNoDescription: "This skill has no description.",
  skillWorkspace: "Repository skill",
  skillUser: "User skill",
  skillMetadata: "Metadata",
  skillFeatures: "Observed features",
  skillDisabled: "Native activation disabled",
  skillDiagnostics: "Some skill files could not be cataloged. Check their paths, size, and SKILL.md metadata.",
  connectionStatus: {
    "not-configured": "Setup required",
    "not-checked": "Not checked",
    ready: "Connection ready",
    blocked: "Connection blocked",
  },
  sessionStatus: {
    idle: "Ready",
    running: "Working",
    "awaiting-permission": "Awaiting permission",
    "awaiting-input": "Awaiting answers",
    interrupted: "Interrupted",
    failed: "Failed",
    closed: "Closed",
    uncertain: "State uncertain",
  } as Readonly<Record<string, string>>,
}
