/** English source strings. Keep product copy here for a future locale layer. */
export const copy = {
  appName: "Harness",
  skipToMessage: "Skip to message",
  userInitial: "Y",
  repository: "Repository",
  chooseRepository: "Open repository",
  repositoryHint: "Choose where this conversation will work.",
  sessions: "Conversations",
  noSessions: "Your conversation will appear here after you connect a runtime.",
  newConversation: "New conversation",
  singleSession: "One conversation is supported in this preview.",
  runtime: "Runtime",
  runtimeSelect: "Choose runtime",
  codex: "Codex",
  claude: "Claude Code",
  connectionChecks: "Connection checks only",
  claudeUnavailable: "Claude Code execution is unavailable. You can check its version and sign-in status here.",
  claudeEmptyTitle: "Connect your Claude Code account.",
  claudeEmptyDescription:
    "Check your installed runtime and sign-in status. Conversations and native Skills activation remain unavailable while billing and managed policy checks are incomplete.",
  openCodePending: "OpenCode · coming next",
  nativeSubscription: "Native subscription",
  localWorkspace: "Local workspace",
  conversation: "Conversation",
  noRepository: "No repository selected",
  refresh: "Refresh connection and context",
  openContext: "Open runtime and context",
  closeContext: "Close context",
  context: "Runtime & context",
  loading: "Connecting to the desktop host…",
  unavailable: "Desktop unavailable",
  missingBridge: "The desktop connection is unavailable. Open Harness from the desktop launcher.",
  failedRequest: "The operation could not be completed. Refresh the connection and try again.",
  dismissError: "Dismiss error",
  emptyTitle: "A workspace for your next idea.",
  emptyDescription: "Open a repository, connect your native runtime, and start a conversation with your code.",
  emptyConfiguredTitle: "Ready when you are.",
  emptyConfiguredDescription:
    "Check your account and execution settings, then start a conversation. Your prompt is only sent when you choose Send.",
  emptySessionTitle: "What are we working on?",
  emptySessionDescription: "Describe the change, ask about this repository, or work through a problem together.",
  emptyFootnote:
    "Your runtime keeps its own account and subscription. Harness never switches to API billing automatically.",
  openSetup: "Set up runtime",
  promptLabel: { codex: "Message to Codex", claude: "Message to Claude Code" },
  promptPlaceholder: "Describe what you want to work on…",
  promptUnavailable: "Start a conversation to send a message…",
  composerHint: "Ctrl + Enter to send",
  composerNote: "Review requests appear in the context panel.",
  send: "Send message",
  interrupt: "Interrupt",
  running: { codex: "Codex is working", claude: "Claude Code is working" },
  awaiting: "Waiting for your review",
  you: "You",
  setup: "Connection",
  authentication: "Account",
  billing: "Billing route",
  overage: "Provider overage",
  unknown: "Unknown",
  subscription: "Subscription",
  observedSubscription: "Subscription observed",
  authenticationStatus: {
    unknown: "Unknown",
    subscription: "Subscription observed",
    authenticated: "Signed in",
    unauthenticated: "Not signed in",
  },
  version: "Version",
  chooseExecutable: { codex: "Choose Codex executable", claude: "Choose Claude Code executable" },
  chooseNativeHome: "Choose native account home",
  selectedExecutable: "Executable",
  selectedNativeHome: "Native account home",
  checkConnection: "Check connection",
  setupHint: {
    codex:
      "Choose your installed Codex executable and the home folder containing .codex, such as C:\\Users\\you. Sign in using Codex before connecting here.",
    claude:
      "Choose your installed Claude Code executable and the home folder containing .claude, such as C:\\Users\\you. Sign in using Claude Code before checking this connection.",
  },
  overageNotice: "Provider overage is unknown. Check your plan and spending settings in Codex before starting.",
  acknowledgeOverage: "I have checked my provider’s spending settings and accept that overage is unknown.",
  allowFileChanges: "Allow file changes in this repository, with review before approval.",
  acknowledgeBoundary: "I understand the operating-system execution boundary is not verified in this preview.",
  modelLabel: "Codex model",
  modelPlaceholder: "Choose a model",
  modelHint: "Models reported by Codex. Availability does not confirm plan access or billing.",
  modelsNotLoaded: "Check connection to load models from your selected Codex runtime.",
  modelsLoading: "Loading models from Codex…",
  modelsUnavailable: "No model catalog is available. Check connection again before starting.",
  modelsUnsupported: "Model selection is unavailable for this runtime.",
  startConversation: "Start conversation",
  sessionStarted: "Conversation connected",
  workspaceReadOnly: "Read-only workspace",
  workspaceWrite: "File changes require review",
  activity: "Activity",
  review: "Review",
  skills: "Skills",
  contextTabs: "Context views",
  activityEmptyTitle: "The work, as it happens",
  activityEmpty: "Tool activity and runtime updates appear here during your conversation.",
  reviewEmptyTitle: "Nothing waiting for review",
  reviewEmpty: "Proposed file changes and questions will appear here when your runtime needs input.",
  fileReview: "File change request",
  permissionReview: "Permission request",
  questionReview: "Your runtime has a question",
  openReview: "Open protected review",
  reviewUnavailable: "Protected review is unavailable. This request can only be declined.",
  questionUnavailable: "Question content is unavailable. Cancel this request to continue safely.",
  reviewed: "Protected content opened",
  expires: "Expires",
  expired: "This review has expired. Open it again to check whether the request is still available.",
  submitAnswers: "Send answers",
  cancelQuestion: "Cancel request",
  movedTo: "Moves to",
  change: { add: "Added", delete: "Deleted", update: "Updated" },
  skillsIntro:
    "Claude Skills discovered in this repository and any selected user skills folder. Discovery is read-only.",
  skillsPending:
    "Skills are cataloged only. Native activation is disabled until runtime execution and policy checks are supported.",
  skillsEmptyTitle: "Bring your Claude Skills",
  skillsEmpty: "Add SKILL.md files under .claude/skills in this repository, or choose a user skills folder.",
  chooseSkillsRoot: "Choose user skills folder",
  skillsWorkspaceMissing: "Open a repository to discover its Claude Skills.",
  skillNoDescription: "This skill has no description.",
  skillWorkspace: "Repository skill",
  skillUser: "User skill",
  skillMetadata: "Metadata",
  skillFeatures: "Observed features",
  skillDisabled: "Native activation disabled",
  skillDiagnostics: "Some skill files could not be cataloged. Check their paths, size, and SKILL.md metadata.",
  connectionStatus: {
    "not-configured": "Setup required",
    "not-checked": "Not checked",
    ready: "Connection ready",
    blocked: "Connection blocked",
  },
  sessionStatus: {
    idle: "Ready",
    running: "Working",
    "awaiting-permission": "Awaiting permission",
    "awaiting-input": "Awaiting answers",
    interrupted: "Interrupted",
    failed: "Failed",
    closed: "Closed",
    uncertain: "State uncertain",
  } as Readonly<Record<string, string>>,
}
